### ISSUE TITLE
F1/F5/F17 - Login/Logout/Register

### ISSUE THREAD

**Issue by Adrian-Perez-98** [AdrianBrambila/CMPE131Team6#2]
This will mostly pertain to the initial startup of the app. A user must sign in in order to make any progress into the taskr app

**Comment by ddot159** [comment]
Had trouble identifying if the user was authenticated was the first issue we had we redirected as a temporary solution. Afterwards we used an is_authenticated method to this.

**Comment by ddot159** [comment]
Remember function broke when it was initially working so we will have to look into this.
