### ISSUE TITLE
F3 - Add/Remove Item

### ISSUE THREAD

**Issue by Adrian-Perez-98** [AdrianBrambila/CMPE131Team6#4]
Within a list in a separate page of where you may add the list, user should be able to remove and add an item to a list.

**Comment by ddot159** [comment]
Toned down the complexity to just adding the task. Another use case will be updated to remove a task. I started working on this and some issues I came up with was how it was missing a table in the debug. How it was fixed : removing the db.app and recreating with db.create_all().

**Comment by Adrian-Perez-98** [comment]
Working on the edit page which will contain an option to delete a task completely.

**Comment by Mohib1402** [comment]
Already finished the adding tasks function with unique functionality for each user, and currently working on deleting the tasks!

**Comment by Mohib1402** [comment]
Now, the website perfectly adds and deletes the tasks!
